version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: books
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapy
    depends_on:
      - mysql
    command: scrapy crawl bookspider

volumes:
  mysql_data:
